services:
  redis:
    image: redis:7-alpine
    container_name: wordaround_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec

  server_a:
    build: ./backend
    container_name: wordaround_server_a
    environment:
      - SERVER_NAME=Server-A
      - REDIS_HOST=redis
      - OTHER_SERVERS=http://server_b:5000,http://server_c:5000
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped



  server_b:
    build: ./backend
    container_name: wordaround_server_b
    environment:
      - SERVER_NAME=Server-B
      - REDIS_HOST=redis
      - OTHER_SERVERS=http://server_a:5000,http://server_c:5000
    ports:
      - "5001:5000"
    depends_on:
      - redis
    restart: unless-stopped


  server_c:
    build: ./backend
    container_name: wordaround_server_c
    environment:
      - SERVER_NAME=Server-C
      - REDIS_HOST=redis
      - OTHER_SERVERS=http://server_a:5000,http://server_b:5000
    ports:
      - "5002:5000"
    depends_on:
      - redis
    restart: unless-stopped


  frontend:
    image: nginx:alpine
    container_name: wordaround_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - server_a
      - server_b
      - server_c

volumes:
  redis_data:
    driver: local
    